### ISSUE TITLE
Fix index.d.ts auto-generation

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-node-backend#5]
Currently it's stopped at 380b90f334ddcffb50582c5774ebf181d6de120a because the generated d.ts has problems. To fully recover the build process, we need to refactor the source structure and make sure superfluous type declarations are not generated.

**Comment by abkieling** [comment]
Is this still an issue?

**Comment by tadayosi** [comment]
I don't remember but it should be fine now :-)
